// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufvvtpmeyvugdscsdqxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmdnZ0cG1leXZ1Z2RzY3NkcXhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNjQ3MzQsImV4cCI6MjA2Mjc0MDczNH0.FGuYjmjZMyyhJMujqqNydwcYOiDi0bQj1raYPDRg_u4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);